/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { DirectPair, DirectPairInterface } from "../DirectPair";

const _abi = [
  {
    anonymous: false,
    inputs: [],
    name: "Test",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "Test1",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220298ffbe2c9b1ab026620e8c518e549e26faa253fb58413031c62e3bb8e07e79f64736f6c63430008110033";

type DirectPairConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DirectPairConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DirectPair__factory extends ContractFactory {
  constructor(...args: DirectPairConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<DirectPair> {
    return super.deploy(overrides || {}) as Promise<DirectPair>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): DirectPair {
    return super.attach(address) as DirectPair;
  }
  override connect(signer: Signer): DirectPair__factory {
    return super.connect(signer) as DirectPair__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DirectPairInterface {
    return new utils.Interface(_abi) as DirectPairInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DirectPair {
    return new Contract(address, _abi, signerOrProvider) as DirectPair;
  }
}
